### ISSUE TITLE
Feature Request - Add ROI support

### ISSUE THREAD

**Issue by gouinK** [igvteam/igv-notebook#12]
Hi all, 

This is a really great package, I was wondering if you have plans to add ROI support, like the one that is described in [this](https://github.com/g2nb/igv-jupyter/issues/44) request?

Thanks!

**Comment by jrobinso** [comment]
Support for ROIs has been added to version 0.4.0.   See https://colab.research.google.com/drive/1vPYBt18S4BZBOrKgoyvEU90nnK7u34TB?usp=sharing for examples
