### ISSUE TITLE
missing requirements

### ISSUE THREAD

**Issue by jamestwebber** [igvteam/igv-notebook#16]
Hello there 👋 This looks really useful, thanks for making it. I wanted to try it out and noticed that there are no requirements specified in `setup.py`, which led to an error on import because `requests` was not installed.

I imagine that this is because you're only using packages that are used by jupyter. In my case I have `jupyterlab` installed in the base conda environment and multiple kernels installed in other environments. I only need `ipykernel` installed in the analysis env, so I didn't have `requests`.

It should be relatively straightforward to add the needed requirements to `setup.py` (I think just `requests` and `ipython`?). I can write a PR if you want

**Comment by jrobinso** [comment]
Thanks, if you can do a PR great.  

Why would ```ipython``` be needed?   I am not really a python developer much less ipython, I assumed that would be available in any environment the notebook would be used.

**Comment by jamestwebber** [comment]
> Why would `ipython` be needed? I am not really a python developer much less ipython, I assumed that would be available in any environment the notebook would be used.

Yeah, I assume so too. But it _does_ get imported, and it seemed silly to add one requirement but not the other. It should be harmless to include, since pip will just see that it's already present.
