### ISSUE TITLE
CRAM version 56 not supported

### ISSUE THREAD

**Issue by emir-radkevich** [igvteam/igv-notebook#21]
Hi.
I tried loading cram in jupyterlab and got an error:
`CRAM version 56 not supported`

Currently using 0.4.5 version.

I am just wondering, what is the easiest workaround for my problem?
Emir.

**Comment by jrobinso** [comment]
That version number doesn't make any sense to me.    Supported CRAM versions are major version 2 and major version 3,  major version 56 is not any Cram format that I know about.   When was this file produced?

**Comment by emir-radkevich** [comment]
> That version number doesn't make any sense to me. Supported CRAM versions are major version 2 and major version 3, major version 56 is not any Cram format that I know about. When was this file produced?

Apparently, it was the file that was not properly trimmed from the big .cram file, so I guess it can be the issue.

**Comment by emir-radkevich** [comment]
> That version number doesn't make any sense to me. Supported CRAM versions are major version 2 and major version 3, major version 56 is not any Cram format that I know about. When was this file produced?

Well, I truncate the file correctly, and the issue is gone. Sorry for disturbing.
