### ISSUE TITLE
igv.js not displaying in 0.5.1

### ISSUE THREAD

**Issue by tmtabor** [igvteam/igv-notebook#23]
When I install igv-notebook 0.5.1, I am seeing an error message every time I attempt to `init()`. See the screenshot below.

<img width="1106" alt="Screen Shot 2023-05-11 at 11 41 42 AM" src="https://github.com/igvteam/igv-notebook/assets/9056964/eed90566-255f-403c-afff-1da302161a6b">

I have yet to go back and re-test older versions of igv-notebook, but I'll update this issue once I have done so.

**Comment by tmtabor** [comment]
Version 0.5.0 seems to work correctly.

**Comment by jrobinso** [comment]
This should be fixed, try importing the latest from master.  I didn't catch this because it works in Colab.  The javascript was legal and when work if imported directly,   I suspect the Jupyter javascript eval function is wrapping the code in another context.

**Comment by tmtabor** [comment]
I have confirmed that 0.5.2 works. Thanks!
