### ISSUE TITLE
How can show soft clipped regions?

### ISSUE THREAD

**Issue by Manuel-DominguezCBG** [igvteam/igv-notebook#27]
First at all, thanks for this powerful combination of tools.

How can I show soft-clipped region in the jupyter.

I need this 

![image](https://github.com/igvteam/igv-notebook/assets/74112779/0c633b50-3b94-465c-83fb-a8ea582aa128)

but I cannot see this in my notebook

![image](https://github.com/igvteam/igv-notebook/assets/74112779/8f454504-491a-4c1e-984d-da34eaaa4d5d)

this is my code

```
import igv_notebook
igv_notebook.init()

b = igv_notebook.Browser(
    {
        "genome": "hg38",
        "locus": "chr22:24,376,166-24,376,456"
    }
)

b.load_track(
    {
        "name": "",
        "path": "/mnt/c/Users/dominm/Desktop/IGV_2.16.2/COSMIC.bam",
        "indexPath": "/mnt/c/Users/dominm/Desktop/IGV_2.16.2/COSMIC.bam.bai",
        "format": "bam",
        "type": "alignment"
    })

b.search('chr17:43094574-43095012')
```

**Comment by jrobinso** [comment]
Sorry for missing this.   Did you read the documentation?  In particular did you try the "showSoftClips" option? 

https://github.com/igvteam/igv.js/wiki/Alignment-Track

**Comment by Manuel-DominguezCBG** [comment]
Yes I found this and I forgot to close this issue. Thank you so much
