### ISSUE TITLE
Just to confirm, could you explain if the data of my BAM files are analysed locally while using this wonderful library.

### ISSUE THREAD

**Issue by Manuel-DominguezCBG** [igvteam/igv-notebook#28]
My command looks like this

![image](https://github.com/igvteam/igv-notebook/assets/74112779/d68a5dde-7250-4a8a-bac3-989f901c4434)
Here the code of that cell

```python
print('BED line: chr3 30606853 30607004 TGFBR2_01F_P5_03')
b = igv_notebook.Browser({'genome': 'hg38', 'locus': 'chr3:30606853-30607004'})
b.load_track({'name': '', 'path': './COSMIC.bam', 'indexPath': './COSMIC.bam.bai', 'format': 'bam', 'type': 'alignment'})
b.search('chr3:30606853-30607004')
```
I need to make sure that all work done is done locally. I am working with patient data.  Am I  sending the reads of my BAM file to IGV web and receiving in the Jupyter notebook the results of IGV web? 

I don't mind if the reference genome is loaded through the internet (it is very efficient by the way well done) but my BAM files must remain local.

If you wonder why I don't just use the locally installed IGV version on my machine. I have created a Python script that automatizes the visualization of regions by using igv-notebook. My script takes the bam file and the bed file and generates a new Jupyter notebook witrh one cell in the notebook for each line found in a BED file given. This allows me to visualised straightaway all regions I want to see.

**Comment by jrobinso** [comment]
It is all local.  igvjs is a pure client app, it runs in your browser

**Comment by jrobinso** [comment]
In other words nothing leaves your web browser.  igv.js (embedded in igv-notebook) pulls resources such as gene annotations from remote servers, but nothing is sent the other direction.

**Comment by Manuel-DominguezCBG** [comment]
Thank you soo much for your prompt replay and thanks for this wonderful tool. I close this 👍
