### ISSUE TITLE
load custom reference genome

### ISSUE THREAD

**Issue by arpanda** [igvteam/igv-notebook#5]
am trying to load a custom reference genome. But getting an error.

Here my test code.

```
import igv_notebook

genome = {
    'reference': {
      "id": "TestGenome",
      "name": "Test1)",
      "fastaURL": "{local fasta path}",
      "indexURL": "{local fasta index path}",
    }
}

igv_notebook.init()
#igv_notebook.loadGenome(genome)

b = igv_notebook.Browser({"genome": "hg19"})
b = igv_notebook.Browser.loadGenome(genome)

```
I learnt about the loadGenome from `igv.js`, looks like its not working.  Any suggestion to fix it.

Thanks
Arijit

**Comment by jrobinso** [comment]
There's not enough information there to help.  Did you read the documentation in this repository's README?   What error are you getting?

**Comment by jrobinso** [comment]
BTW there is no "loadGenome" python function, please review the README.

**Comment by arpanda** [comment]
For the `igv_notebook.loadGenome(genome)`, the error is 
```
AttributeError: module 'igv_notebook' has no attribute 'loadGenome'
```
and for `b = igv_notebook.Browser.loadGenome(genome)`, the error is 
```
AttributeError: type object 'Browser' has no attribute 'loadGenome'
```

I was trying to follow [this](https://github.com/igvteam/igv.js/wiki/Browser-API-2.0#loadgenome) documentation. 

My main goal is to load a custom reference genome from a fasta file. but not sure how to do it using `igv_notebook `. 

Thanks

**Comment by jrobinso** [comment]
The documentation you reference is for igv.js,  there is no loadGenome function in igv-notebook.  Your second example is the correct way to do this.   See the README section on URLs and Paths.    I will try your case and create an example but it might be tomorrow before I can do this.

**Comment by jrobinso** [comment]
I've added example notebooks for defining a custom reference for Jupyter and Colab,  see the examples directly.   Be sure you understand the use of "path" and "url" fields as explained in the README.   If using Jupyter Notebook or Lab you can use URLs if the files in are in the directory tree relative where you started the server.   If using Colab you musth use paths.
