### ISSUE TITLE
feature request for exporting the igv-browser visualization 

### ISSUE THREAD

**Issue by KalinNonchev** [igvteam/igv-notebook#8]
Hello IGV-notebook team,

Thanks for this great package!
I have the following case:
When I am doing analysis and I look at specific genomic coordinates, often I want to share the **jupyter notebook as html** directly with the collaborators. 
However, when I export the notebook as html file, the output of igv-notebook is missing. 
It would be nice and very useful to **export the igv-browser visualization**. Would it be possible to render the javascript to an image so that it is visible in the html file under the code cell? 

Best,

**Comment by jrobinso** [comment]
I will look into this.
